### ISSUE TITLE
What should replace the "DANDI_CACHE" environment variable?

### ISSUE THREAD

**Issue by jwodder** [con/fscacher#3]
When a new `PersistentCache` is constructed, the code currently checks the value of the `DANDI_CACHE` environment variable.  If it is "`clear`", the cache is cleared; if it is "`ignore`", memoization is a no-op.  Should the fscacher library continue to perform these actions based on the value of an environment variable, and, if so, what should the variable be renamed to?

One possible way to handle this:
* Remove the `DANDI_CACHE` and `_ignore_cache` code from fscacher
* Add to fscacher a `NullCache` class that is API-compatible with `PersistentCache` but does nothing
* In dandi, replace all constructions of a `PersistentCache` instance with a call to a `get_persistent_cache()` function which checks `DANDI_CACHE` and, based on its value, returns either a `PersistentCache` instance, a `NullCache` instance, or a `PersistentCache` instance on which `clear()` has been called.

**Comment by yarikoptic** [comment]
Sounds right.  But since (hopefully) fscacher might be used by multiple projects (possibly at the same run time) I think that  fscacher should still provide a convenience to clear (or ignore) all caches so user or developer could "centralize" their control over fscacher operation. So allowing for some env var (e.g. FSCACHER_CACHE) to provide a global override could still be of value.
I also think that I did use `ignore` mode a good number of times during troubleshooting so I do not completely obliterate the cache, thus I am not sure if split into PersistentCache and NullCache would be sufficient.

What about
- add `.set_mode(mode=None)` to PersistentCache which would `mode = os.environ.get("FSCACHER_CACHE", mode).lower()` and then (re)set `self._ignore_cache` .  This would allow to override any provided `mode` with FSCACHER. It would be called from its `__init__`
- add a `@staticmethod` `.get_custom_cache(package_name, *args, **kwargs)` which would pretty much implement what you proposed for `get_persistent_cache`  -- create PersistentCache, consult `NAME_CACHE` variable (be it for DANDI or DATALAD), and call `.set_mode` on it?  Then corresponding package could use `partial` on it as its PersistentCache constructor.  

comes out a bit ugly, doubles the `set_mode` call... not 100% certain about it - may be you see a better pattern to use here?  

e.g. we could just add a kwarg `package="FSCACHER"` to `__init__`, and then packages could use partial on constructor (or have their own helper indeed) but that would prevent "global" control over fscacher (well -- logic could be added of cause, e.g. `mode = os.environ.get("FSCACHER_CACHE", os.environ.get("%s_CACHE" % package.upper())).lower()` to have both.

**Comment by jwodder** [comment]
@yarikoptic Yet another idea: The `__init__` method takes an optional `envvar` argument giving the name of a library-specific control environment variable.  The method then retrieves the value of this environment variable, falling back to the `FSCACHER_CACHE` environment variable if `envvar` is `None` or if the specified variable is not set, and it then disables or clears the cache as specified.

**Comment by yarikoptic** [comment]
Sounds good too. I went through the ideas and now forgot why I didn't mention this one, which we use for logger in datalad as well. And I don't see shortcomings ATM: partial could always be established for convenience by corresponding package
