### ISSUE TITLE
Q: does joblib memoization works across python versions? 

### ISSUE THREAD

**Issue by yarikoptic** [con/fscacher#36]
or we would need to make caches python version specific?

**Comment by jwodder** [comment]
It appears that joblib uses pickle with the [default protocol version](https://docs.python.org/3/library/pickle.html#pickle.DEFAULT_PROTOCOL), which is either version 3 or version 4, depending on Python version, but both versions have been available since Python 3.4, so the memoization should work across all Python versions fscacher supports.

**Comment by yarikoptic** [comment]
Great, thank you @jwodder!
